#!/bin/bash

### BEGIN INIT INFO
# Provides:       bucket_server
# Required-Start: $network
# Required-Stop:
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: bucket_server
### END INIT INFO

## EDIT THIS SECTION
USER="***EDITME***"                     # User that runs the bucket server
BUCKET_BIN="***EDITME***/bucket_server" # Path to the compiled binary
BUCKET_CONFIG_FILE="***EDITME***"       # Path to the config file

NAME="bucket_server"                    # Reusable name
BUCKET_LOG_FILE="/var/log/${NAME}.log"  # Path to the log file
BUCKET_PID_FILE="/var/run/${NAME}.pid"  # Path to the pid file

recursiveKill() { # Recursively kill a process and all subprocesses
    CPIDS=$(pgrep -P $1);
    for PID in $CPIDS
    do
        recursiveKill $PID $2
    done
    kill $2 $1 2>/dev/null
}

case "$1" in
      start)
        echo "Starting $NAME ..."
        if [ -f "$BUCKET_PID_FILE" ]
        then
            echo "Already running according to $BUCKET_PID_FILE"
            exit 1
        fi
        /bin/su -m -l $USER -c "$BUCKET_BIN $BUCKET_CONFIG_FILE" >> "$BUCKET_LOG_FILE" 2>&1 &
        PID=$!
        echo $PID > "$BUCKET_PID_FILE"
        echo "Started with pid $PID - Logging to $BUCKET_LOG_FILE" && exit 0
        ;;
      stop)
        echo "Stopping $NAME ..."
        if [ ! -f "$BUCKET_PID_FILE" ]
        then
            echo "Already stopped!"
            exit 1
        fi
        PID=`cat "$BUCKET_PID_FILE"`
        recursiveKill $PID -9
        rm -f "$BUCKET_PID_FILE"
        echo "Stopped $NAME" && exit 0
        ;;
      restart)
        $0 stop
        sleep 1
        $0 start
        ;;
      reload)
        PID=`cat "$BUCKET_PID_FILE"`
        echo "Reloading config file $BUCKET_CONFIG_FILE for pid $PID"
        recursiveKill $PID -1
        ;;
      status)
        if [ -f "$BUCKET_PID_FILE" ]
        then
            PID=`cat "$BUCKET_PID_FILE"`
            if [ "$(/bin/ps --no-headers -p $PID)" ]
            then
                echo "$NAME is running (pid : $PID)" && exit 0
            else
                echo "Pid $PID found in $BUCKET_PID_FILE, but not running." && exit 1
            fi
        else
            echo "$NAME is NOT running" && exit 1
        fi
    ;;
      *)
      echo "Usage: /etc/init.d/$NAME {start|stop|restart|reload|status}" && exit 1
      ;;
esac

exit 0
